"""empty message

Revision ID: 111055e2e215
Revises: 56cdab531577
Create Date: 2023-11-15 19:37:11.339305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111055e2e215'
down_revision = '56cdab531577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.String(length=80), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=180),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=180),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('salt')

    # ### end Alembic commands ###
